---
- name: Delete alfresco dir for sec_installation
  shell: rm -rf {{alfresco_work_dir}}

- name: Clone alfresco in Websoft9 
  git:
    repo: "{{alfresco_git_url}}"
    dest: "{{alfresco_work_dir}}"

- name: Create dir for alfresco
  file: 
    state: directory
    path: "{{item}}"
  loop: 
    - '{{alfresco_work_dir}}/volumes'
    - /data/db/postgresql

- name: Change alfresco site url
  shell: |
    public_ip=`wget -O - https://download.websoft9.com/ansible/get_ip.sh | bash`
    sudo sed -i "s/APP_SITE_URL=.*/APP_SITE_URL=$public_ip/g" .env
  args:
    chdir: '{{alfresco_work_dir}}'

- name: Run docker-compose 
  shell: |  
    docker-compose up -d
    sleep 30
  args:
    chdir: '{{alfresco_work_dir}}'

# alfresco nginx rewrite setting and restart nginx
- name: Alfresco nginx rewrite setting
  lineinfile:
    path: /etc/nginx/conf.d/default.conf
    regexp: '^.*proxy_pass.*$'
    line: 'rewrite ^ $scheme://$host:8080/share/page;'
    state: present
    backrefs: yes

- name: Restarted nginx
  shell: systemctl restart nginx

- name: Copy encryption.py script
  copy:
    src: encryption.py
    dest: /opt/encryption.py

- name: Copy check postgresql table exists script
  copy:
    src: check_postgresql_table.sh
    dest: /opt/check_postgresql_table.sh

- name: Install passlib module for random password
  pip: 
    name: passlib

- name: Set soft link for alfresco
  file:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    state: link
    force: yes
  with_items:
  - {src: '{{alfresco_work_dir}}/volumes/postgres/data/',dest: /data/db/postgresql/data}
  - {src: '{{alfresco_work_dir}}/volumes/postgres/logs/',dest: /data/db/postgresql/logs}
  - {src: '{{alfresco_work_dir}}/volumes/postgres/logs/',dest: /data/logs/postgresql}

# check service and version
- name: Check alfresco service 
  shell: docker ps -a 
  register: check_alfresco_service
  notify: check_alfresco_service
    
- name: Check alfresco version
  shell: |
    sudo echo "alfresco version:" $(docker images |grep alfresco-share |awk '{print $2}') |sudo tee -a /data/logs/install_version.txt  

- name: Check activemq version
  shell: |
    sudo echo "activemq version:" $(docker images |grep alfresco-activemq |awk '{print $2}') |sudo tee -a /data/logs/install_version.txt  

- name: Check postgresql version
  shell: |
    sudo echo "postgresql version:" $(docker images |grep postgres |awk '{print $2}') |sudo tee -a /data/logs/install_version.txt  

    